FROM node:20-alpine

# Install 9router secara global
RUN npm install -g 9router

# Expose port yang digunakan oleh 9router
EXPOSE 20128

# Perintah default untuk menjalankan 9router dengan flag headless
CMD ["9router", "--no-browser", "--log", "--skip-update"]
